### ISSUE TITLE
Server酱Error

### ISSUE THREAD

**Issue by drpasserby** [Bertramoon/DGUT_Auto_Report#4]
Github错误信息：
report
Process completed with exit code 2.

一旦添加了SERVER_KEY就会报错（删掉又正常打卡了）

**Comment by Bertramoon** [comment]
可能是SERVER_KEY的值设置有误，你再检查看看，具体格式如下：
`-K key1,key2,……,keyN`
其中，-K和key1中间有空格，key1和key2中间只能有逗号，不能有空格

**Comment by drpasserby** [comment]
是每个人都需要key吗？我只在SERVER_KEY里面设置了一个key

**Comment by Bertramoon** [comment]
是的，如果只设置一个key的话，只会给第一个账号进行推送，其他账号不会进行推送。详情请点击[这里](https://gitee.com/bertramoon/dgut-autoreport-configure/blob/master/README.md)，查看最后的一段，有具体说明

**Comment by drpasserby** [comment]
好的，已经看到了~（之前貌似没注意到）

**Comment by Bertramoon** [comment]
嗯嗯没事~

**Comment by drpasserby** [comment]
测试完毕，之前貌似key前面是没加-K，所以导致Error

**Comment by Bertramoon** [comment]
嗯嗯，搞定了就好
