### ISSUE TITLE
更改位置信息后脚本不能提交

### ISSUE THREAD

**Issue by 4674ghkbvgy** [Bertramoon/DGUT_Auto_Report#6]
![2022-01-13 16-07-02 的屏幕截图](https://user-images.githubusercontent.com/72641410/149292946-82055e62-5bc0-4159-8692-880a35a96ebb.png)
寒假回家修改成不在校内之后就不能自动打卡了
我用肮脏的方法调试了一下，卡在19行那里了
有什么办法解决吗

**Comment by Bertramoon** [comment]
请先fork一下最新版看有没有问题，你这个有可能是版本问题或者环境问题
